### ISSUE TITLE
Framer Motion peer dependency

### ISSUE THREAD

**Issue by snelsi** [creatorslook/untitledui-js#4]
This library lists [Framer Motion](https://www.framer.com/motion) as a dependency in [package.json](https://github.com/creatorslook/untitledui-js/blob/master/package.json). 
Framer Motion is a giant library bundle-size-wise, and you don't want to bake it in the build.
Instead, it should be listed as a peer dependency and excluded from the bundle.

**Comment by creatorslook** [comment]
The Library has been updated and with proper dependency management, thank you @snelsi

**Comment by snelsi** [comment]
Well, you still list 'react' as a 'dependency'. But I guess it's a progress nonetheless
