### ISSUE TITLE
Please add HomeLine icon

### ISSUE THREAD

**Issue by charismanapriandi** [creatorslook/untitledui-js#5]
missing icon:

![image](https://github.com/creatorslook/untitledui-js/assets/68155110/2565d49d-7c7d-4e25-b667-4c3d7e4f29c8)

**Comment by robertalv** [comment]
Added #6

**Comment by robertalv** [comment]
@charismanapriandi #6 has been pushed. This can be closed.

**Comment by creatorslook** [comment]
The issue has been closed
