### ISSUE TITLE
Development Section Icon 

### ISSUE THREAD

**Issue by charismanapriandi** [creatorslook/untitledui-js#7]
Hi guys, thanks to response my previous issues.

You may forget this section and please update the package on NPM 🙂

<img width="673" alt="image" src="https://github.com/creatorslook/untitledui-js/assets/68155110/26e25a18-e952-49ba-af15-ec2230ce4b0e">

**Comment by robertalv** [comment]
You can find that section here: [development icons](https://github.com/creatorslook/untitledui-js/blob/master/src/icons/development.tsx)

**Comment by robertalv** [comment]
@creatorslook You can close this issue
