### ISSUE TITLE
Can't render Icons using React SSR

### ISSUE THREAD

**Issue by moalo** [creatorslook/untitledui-js#9]
Hello! 🙂

I have a basic Next.js project and tried to use this icon pack. Unfortunately, this breaks Next's SSR as the components returned from this library contain client-side only code using e.g. `useEffect`.

There's a section for package developers within the Next.js docs.
https://nextjs.org/docs/getting-started/react-essentials#third-party-packages

To make it work it's probably sufficient to just use the `"use client"` directive on your end.

But in my humble opinion, I think importing SVGs from this package into a project using SSR should be supported in general.

<img width="741" alt="Screenshot 2023-07-24 at 15 09 31" src="https://github.com/creatorslook/untitledui-js/assets/31535518/7fb6bf1e-e04c-4cbd-ae83-aba758fd3ac2">

**Comment by creatorslook** [comment]
Thank you @maolo for raising this issue, the library will be updated very soon

**Comment by creatorslook** [comment]
Hey @Maolo the issue has been resolved, please update the untitledui-js library in your dependencies to see the changes , Thank you for raising the issue
